version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - order
      - sale
  auth:
    build:
      context: ./auth
    restart: on-failure
    ports:
      - 4001:4000
    volumes:
      - ./auth:/app
  order:
    build:
      context: ./order
    restart: on-failure
    ports:
      - 4002:4000
    volumes:
      - ./order:/app
  sale:
    build:
      context: ./sale
    restart: on-failure
    ports:
      - 4003:4000
    volumes:
      - ./sale:/app
